name: Build and Push Backend to DockerHub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: roadmvn

jobs:
  build_and_push_backend:
    name: Build and Push Backend Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build et Push de l'image Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/student-backend:latest 